exclude unused modules when building with pyinstaller
without this even building older versions like v2.4.0 breaks because it can't find some tcl script:

 ~/Desktop λ /Users/tybug/Desktop/coding/osu/circleguard/dist/Circleguard ; exit;
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth__tkinter.py", line 28, in <module>
FileNotFoundError: Tcl data directory "/var/folders/t1/415srbnx62b2h3f1kx00n66w0000gn/T/_MEIBPzdNi/tcl" not found.
[7781] Failed to execute script pyi_rth__tkinter

I have no idea why. It's very concerning actually.